; 2 - LED Output with break

LDI		R18, LOW(RAMEND)	; Initialize stack pointer
OUT		SPL, R18
LDI		R18, HIGH(RAMEND)
OUT		SPH, R18


LDI R16, 0XFF

OUT DDRD, R16 ; PORT D AS OUTPUT 
LDI R16, 0
OUT DDRA, R16 ; PORT A AS INTPUT
OUT DDRB, R16 ; PORT B AS INTPUT

LDI R26, 0X87
OUT ADCSRA, R26; ENABLE ADC AND USING CK/128
LDI R16, 0X20 ; 0010 0000  ,,,, USING REF = 5V, ADLAR = left justified = 1 `
OUT ADMUX, R16

READ_ADC:
	SBI ADCSRA, ADSC  ; START ADC

KEEP_POLLING:
    SBIS ADCSRA, ADIF
	RJMP KEEP_POLLING

	SBI ADCSRA, ADIF
	
	IN R16, ADCH
	
	COM R16
	OUT PORTD, R16

	SBIC PINB, 0 ; Checking sw0
	RJMP READ_ADC



	EXIT:RJMP EXIT