;Cole Matthews
; DAC

INITIALIZE:
LDI R16, HIGH(RAMEND)
OUT SPH, R16
LDI R16, LOW(RAMEND)
OUT SPL, R16
SLEEP
SER R16
OUT DDRB, R16
CLR R16
OUT PORTB, R16
CBI DDRA, 0
SBI PORTA, 0

/*dactest:
LDI R19, 0b10001000
OUT PORTB, R19
L1:RJMP L1

dactest2:
LDI R19, 0xFA
OUT PORTB, R19
L2:RJMP L2*/

MAIN:
;CALL STWAVE
;CALL SLOWSTWAVE
;CALL FASTSTWAVE
;CALL HALFSTWAVE
CALL TWAVE
L3:RJMP L3
;=========================================================
TWAVE:
	CLR R17	;INITIALIZES VOLTAGE OUT REGISTER
TWAVELOOP:
	TWAVELOOPINCEXTRA:
		NOP
	TWAVELOOPINC:
		SBIS PINA, 0	;CHECKS IF SWITCH 0 IS PRESSED
		JMP EXIT	;EXITS LOOP IF 
		OUT PORTB, R17	;UPDATES VOLTAGE
		INC R17;INCREASES VOLTAGE REGISTER BY 0.01V
		NOP
		CPI R17, 255
		BREQ TWAVELOOPDECEXTRA
		RJMP TWAVELOOPINC
	TWAVELOOPDECEXTRA:
		NOP
	TWAVELOOPDEC:
		SBIS PINA, 0	;CHECKS IF SWITCH 0 IS PRESSED
		JMP EXIT	;EXITS LOOP IF 
		OUT PORTB, R17	;UPDATES VOLTAGE
		DEC R17;INCREASES VOLTAGE REGISTER BY 0.01V
		NOP
		CPI R17, 0
		BREQ TWAVELOOPINCEXTRA
		RJMP TWAVELOOPDEC
;=========================================================
STWAVE:	;LOOPS EVERY 20uS, VOLTAGE FROM 0V-2.55V
	CLR R17	;INITIALIZES VOLTAGE OUT REGISTER
STWAVELOOP:
	SBIS PINA, 0	;CHECKS IF SWITCH 0 IS PRESSED
	JMP EXIT	;EXITS LOOP IF 
	OUT PORTB, R17	;UPDATES VOLTAGE
	INC R17	;INCREASES VOLTAGE REGISTER BY 0.01V
	CALL STWAVEDELAY	;ADDS 13uS OF DELAY
	RJMP STWAVELOOP	;RESTARTS THE CYCLE

STWAVEDELAY:	;USED TO ADD DELAY TO STWAVE
	NOP
	NOP
	NOP
	NOP
	NOP
	RET
;=========================================================
HALFSTWAVE:	;LOOPS EVERY 20uS, VOLTAGE FROM 0V-1.27V
	CLR R17	;INITIALIZES TALLY OUT REGISTER
HALFSTWAVELOOP:
	SBIS PINA, 0	;CHECKS IF SWITCH 0 IS PRESSED
	JMP EXIT	;EXITS LOOP IF 
	MOV R18, R17	;COPIES THE TALLY REGISTER
	LSR R18	;HALVES VALUE OF TALLY REG TO GET VOLTAGE REG
	OUT PORTB, R18	;UPDATES VOLTAGE
	INC R17	;INCREASES TALLY REGISTER BY 1
	CALL HALFSTWAVEDELAY
	RJMP HALFSTWAVELOOP

HALFSTWAVEDELAY:	;USED TO ADDD DELAY TO HALFSTWAVE
	NOP
	NOP
	NOP
	RET
;=========================================================
FASTSTWAVE:	;LOOPS EVERY 10uS, VOLTAGE FROM 0V-2.55V
	CLR R17	;INITIALIZES VOLTAGE OUT REGISTER
FASTSTWAVELOOP:
	SBIS PINA, 0	;CHECKS IF SWITCH 0 IS PRESSED
	JMP EXIT	;EXITS LOOP IF 
	OUT PORTB, R17	;UPDATES VOLTAGE
	INC R17	;INCREASES VOLTAGE REGISTER BY 0.01V
	NOP	;ADDS DELAY
	NOP	;TOTAL "NOP" DELAY = 4 CYCLES
	NOP
	RJMP FASTSTWAVELOOP	;RESTARTS THE CYCLE
;=========================================================
SLOWSTWAVE:	;LOOPS EVERY 20uS, VOLTAGE FROM 0V-2.55V
	CLR R17	;INITIALIZES VOLTAGE OUT REGISTER
SLOWSTWAVELOOP:
	SBIS PINA, 0	;CHECKS IF SWITCH 0 IS PRESSED
	JMP EXIT	;EXITS LOOP IF 
	OUT PORTB, R17	;UPDATES VOLTAGE
	INC R17	;INCREASES VOLTAGE REGISTER BY 0.01V
	CALL SLOWSTWAVEDELAY	;ADDS 14uS OF DELAY
	RJMP SLOWSTWAVELOOP	;RESTARTS THE CYCLE

SLOWSTWAVEDELAY:	;USED TO ADD DELAY TO STWAVE
	LDI R18, 0x08	;SETS #OF LOOPS TO 8
	NOP
	SlowSTWaveDelayLoop:;ADDS 2+(#LOOPS-1)*3 uS OF DELAY
		DEC R18	;ADDS 1uS PER LOOP
		BRNE SlowSTWaveDelayLoop	
		;ADDS 2uS FOR ALL BUT LAST LOOP(1uS)
	RET
;=========================================================
EXIT:	;USED TO STOP WAVEFORM
	CLR R16	;CLEARS R16
	OUT PORTB, R16	;SETS OUTPUT VOLTAGE TO 0v
	RET	;RETURNS TO MAIN
;=========================================================
